-- ============================================================
-- CLUB_ANNOUNCEMENTS table – for club admins only
-- Club admins can only manage their club's rows. Admins can manage all.
-- Run in Supabase Dashboard → SQL Editor
-- ============================================================

-- ---------------------------------------------------------------------------
-- 1. TABLE: club_announcements (club_id required; one table per club content)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.club_announcements (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title text NOT NULL,
  subtitle text NULL,
  image_url text NOT NULL DEFAULT 'https://stock.adobe.com/th/search?k=image'::text,
  date date NULL DEFAULT now(),
  see_more_url text NULL,
  category text NULL,
  created_at timestamptz NULL DEFAULT now(),
  club_id bigint NOT NULL REFERENCES public.clubs (id) ON DELETE CASCADE,
  created_by_role text NULL CHECK (created_by_role IN ('admin', 'club_admin')),
  created_by_user_id uuid NULL REFERENCES auth.users (id) ON DELETE SET NULL,
  CONSTRAINT club_announcements_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

COMMENT ON TABLE public.club_announcements IS 'Announcements managed by club admins. Each row belongs to one club. Only club_admin (for their club) and admin can modify.';


-- ---------------------------------------------------------------------------
-- 2. ROW LEVEL SECURITY (RLS)
-- ---------------------------------------------------------------------------

ALTER TABLE public.club_announcements ENABLE ROW LEVEL SECURITY;


-- ---------------------------------------------------------------------------
-- 3. RLS POLICIES
-- Public read. Admin: full access. Club admin: only rows where club_id = their club_id.
-- ---------------------------------------------------------------------------

-- Anyone can read club announcements (public page)
DROP POLICY IF EXISTS "Anyone can read club_announcements" ON public.club_announcements;
CREATE POLICY "Anyone can read club_announcements"
  ON public.club_announcements FOR SELECT
  USING (true);

-- Admin can insert any club
DROP POLICY IF EXISTS "Admin can insert club_announcements" ON public.club_announcements;
CREATE POLICY "Admin can insert club_announcements"
  ON public.club_announcements FOR INSERT
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
  );

-- Club admin can only insert for their club
DROP POLICY IF EXISTS "Club admin can insert own club_announcements" ON public.club_announcements;
CREATE POLICY "Club admin can insert own club_announcements"
  ON public.club_announcements FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.user_id = auth.uid() AND ur.role = 'club_admin' AND ur.club_id IS NOT NULL AND ur.club_id = club_announcements.club_id
    )
  );

-- Admin can update any
DROP POLICY IF EXISTS "Admin can update club_announcements" ON public.club_announcements;
CREATE POLICY "Admin can update club_announcements"
  ON public.club_announcements FOR UPDATE
  USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
  );

-- Club admin can update only their club's rows
DROP POLICY IF EXISTS "Club admin can update own club_announcements" ON public.club_announcements;
CREATE POLICY "Club admin can update own club_announcements"
  ON public.club_announcements FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.user_id = auth.uid() AND ur.role = 'club_admin' AND ur.club_id = club_announcements.club_id
    )
  );

-- Admin can delete any
DROP POLICY IF EXISTS "Admin can delete club_announcements" ON public.club_announcements;
CREATE POLICY "Admin can delete club_announcements"
  ON public.club_announcements FOR DELETE
  USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
  );

-- Club admin can delete only their club's rows
DROP POLICY IF EXISTS "Club admin can delete own club_announcements" ON public.club_announcements;
CREATE POLICY "Club admin can delete own club_announcements"
  ON public.club_announcements FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.user_id = auth.uid() AND ur.role = 'club_admin' AND ur.club_id = club_announcements.club_id
    )
  );


-- ---------------------------------------------------------------------------
-- 4. GRANTS
-- ---------------------------------------------------------------------------

GRANT SELECT ON public.club_announcements TO anon, authenticated;
GRANT ALL ON public.club_announcements TO authenticated;
