-- ============================================================
-- FULL SQL SCHEMA – run in Supabase Dashboard → SQL Editor
-- Creates tables, RLS, functions, and grants for the app.
-- ============================================================

-- ---------------------------------------------------------------------------
-- 1. TABLES (order: no deps first, then dependents)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.international_programs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  image_url text NULL DEFAULT 'https://stock.adobe.com/search?k=no+image'::text,
  name_line1 text NULL,
  name_line2 text NULL,
  CONSTRAINT international_programs_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.clubs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text NULL,
  description text NULL,
  image_url text NULL,
  created_at timestamptz NOT NULL DEFAULT (now() AT TIME ZONE 'utc'::text),
  managed_by text NULL,
  CONSTRAINT clubs_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.announcements (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title text NOT NULL,
  subtitle text NULL,
  image_url text NOT NULL DEFAULT 'https://stock.adobe.com/th/search?k=image'::text,
  date date NULL DEFAULT now(),
  see_more_url text NULL,
  category text NULL,
  created_at timestamptz NULL,
  club_id bigint NULL,
  created_by_role text NULL CHECK (created_by_role IN ('admin', 'club_admin')),
  created_by_user_id uuid NULL REFERENCES auth.users (id) ON DELETE SET NULL,
  CONSTRAINT announcements_pkey PRIMARY KEY (id),
  CONSTRAINT announcements_club_id_fkey FOREIGN KEY (club_id) REFERENCES public.clubs (id)
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.club_announcements (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title text NOT NULL,
  subtitle text NULL,
  image_url text NOT NULL DEFAULT 'https://stock.adobe.com/th/search?k=image'::text,
  date date NULL DEFAULT now(),
  see_more_url text NULL,
  category text NULL,
  created_at timestamptz NULL DEFAULT now(),
  club_id bigint NOT NULL REFERENCES public.clubs (id) ON DELETE CASCADE,
  created_by_role text NULL CHECK (created_by_role IN ('admin', 'club_admin')),
  created_by_user_id uuid NULL REFERENCES auth.users (id) ON DELETE SET NULL,
  CONSTRAINT club_announcements_pkey PRIMARY KEY (id),
  CONSTRAINT club_announcements_club_id_fkey FOREIGN KEY (club_id) REFERENCES public.clubs (id) ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.user_roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  role text NOT NULL CHECK (role IN ('admin', 'club_admin')),
  club_id bigint NULL REFERENCES public.clubs (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT user_roles_user_id_key UNIQUE (user_id)
) TABLESPACE pg_default;

-- Add created_by columns if table already existed without them (must run before any COMMENT on these columns)
ALTER TABLE public.announcements
  ADD COLUMN IF NOT EXISTS created_by_role text NULL;
ALTER TABLE public.announcements
  ADD COLUMN IF NOT EXISTS created_by_user_id uuid NULL REFERENCES auth.users (id) ON DELETE SET NULL;

-- Add check constraint only if column was just added (avoid error if constraint already exists)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'announcements_created_by_role_check'
    AND conrelid = 'public.announcements'::regclass
  ) THEN
    ALTER TABLE public.announcements
      ADD CONSTRAINT announcements_created_by_role_check
      CHECK (created_by_role IS NULL OR created_by_role IN ('admin', 'club_admin'));
  END IF;
END $$;

COMMENT ON TABLE public.user_roles IS 'Stores admin vs club_admin role; club_id set only for club_admin.';
COMMENT ON COLUMN public.announcements.created_by_role IS 'Role of the user who created this announcement.';
COMMENT ON COLUMN public.announcements.created_by_user_id IS 'Auth user id of the creator.';


-- ---------------------------------------------------------------------------
-- 2. ROW LEVEL SECURITY (RLS)
-- ---------------------------------------------------------------------------

ALTER TABLE public.international_programs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clubs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.club_announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;


-- ---------------------------------------------------------------------------
-- 3. HELPER: current user role and club_id
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.current_user_role()
RETURNS TABLE (role text, club_id bigint)
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT ur.role, ur.club_id
  FROM public.user_roles ur
  WHERE ur.user_id = auth.uid();
$$;


-- ---------------------------------------------------------------------------
-- 4. RLS POLICIES – user_roles (users read own row only; insert/update/delete via SQL or assign_user_role)
-- ---------------------------------------------------------------------------

DROP POLICY IF EXISTS "Users can read own role" ON public.user_roles;
CREATE POLICY "Users can read own role"
  ON public.user_roles FOR SELECT
  USING (auth.uid() = user_id);


-- ---------------------------------------------------------------------------
-- 5. RLS POLICIES – international_programs (public read; admin write)
-- ---------------------------------------------------------------------------

DROP POLICY IF EXISTS "Anyone can read international_programs" ON public.international_programs;
CREATE POLICY "Anyone can read international_programs"
  ON public.international_programs FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Admin can insert international_programs" ON public.international_programs;
CREATE POLICY "Admin can insert international_programs"
  ON public.international_programs FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin'));

DROP POLICY IF EXISTS "Admin can update international_programs" ON public.international_programs;
CREATE POLICY "Admin can update international_programs"
  ON public.international_programs FOR UPDATE
  USING (EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin'));

DROP POLICY IF EXISTS "Admin can delete international_programs" ON public.international_programs;
CREATE POLICY "Admin can delete international_programs"
  ON public.international_programs FOR DELETE
  USING (EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin'));


-- ---------------------------------------------------------------------------
-- 6. RLS POLICIES – clubs (public read; admin write)
-- ---------------------------------------------------------------------------

DROP POLICY IF EXISTS "Anyone can read clubs" ON public.clubs;
CREATE POLICY "Anyone can read clubs"
  ON public.clubs FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Admin can insert clubs" ON public.clubs;
CREATE POLICY "Admin can insert clubs"
  ON public.clubs FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin'));

DROP POLICY IF EXISTS "Admin can update clubs" ON public.clubs;
CREATE POLICY "Admin can update clubs"
  ON public.clubs FOR UPDATE
  USING (EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin'));

DROP POLICY IF EXISTS "Admin can delete clubs" ON public.clubs;
CREATE POLICY "Admin can delete clubs"
  ON public.clubs FOR DELETE
  USING (EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin'));


-- ---------------------------------------------------------------------------
-- 7. RLS POLICIES – announcements (public read; admin full access; club_admin own club only)
-- ---------------------------------------------------------------------------

DROP POLICY IF EXISTS "Anyone can read announcements" ON public.announcements;
CREATE POLICY "Anyone can read announcements"
  ON public.announcements FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Admin can insert announcements" ON public.announcements;
CREATE POLICY "Admin can insert announcements"
  ON public.announcements FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin'));

DROP POLICY IF EXISTS "Club admin can insert own club announcements" ON public.announcements;
CREATE POLICY "Club admin can insert own club announcements"
  ON public.announcements FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.user_id = auth.uid() AND ur.role = 'club_admin' AND ur.club_id IS NOT NULL AND ur.club_id = announcements.club_id
    )
  );

DROP POLICY IF EXISTS "Admin can update announcements" ON public.announcements;
CREATE POLICY "Admin can update announcements"
  ON public.announcements FOR UPDATE
  USING (EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin'));

DROP POLICY IF EXISTS "Club admin can update own club announcements" ON public.announcements;
CREATE POLICY "Club admin can update own club announcements"
  ON public.announcements FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.user_id = auth.uid() AND ur.role = 'club_admin' AND ur.club_id = announcements.club_id
    )
  );

DROP POLICY IF EXISTS "Admin can delete announcements" ON public.announcements;
CREATE POLICY "Admin can delete announcements"
  ON public.announcements FOR DELETE
  USING (EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin'));

DROP POLICY IF EXISTS "Club admin can delete own club announcements" ON public.announcements;
CREATE POLICY "Club admin can delete own club announcements"
  ON public.announcements FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.user_id = auth.uid() AND ur.role = 'club_admin' AND ur.club_id = announcements.club_id
    )
  );

-- ---------------------------------------------------------------------------
-- 7b. RLS POLICIES – club_announcements (public read; admin full; club_admin own club only)
-- ---------------------------------------------------------------------------

DROP POLICY IF EXISTS "Anyone can read club_announcements" ON public.club_announcements;
CREATE POLICY "Anyone can read club_announcements"
  ON public.club_announcements FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin can insert club_announcements" ON public.club_announcements;
CREATE POLICY "Admin can insert club_announcements"
  ON public.club_announcements FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin'));

DROP POLICY IF EXISTS "Club admin can insert own club_announcements" ON public.club_announcements;
CREATE POLICY "Club admin can insert own club_announcements"
  ON public.club_announcements FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.user_id = auth.uid() AND ur.role = 'club_admin' AND ur.club_id IS NOT NULL AND ur.club_id = club_announcements.club_id
    )
  );

DROP POLICY IF EXISTS "Admin can update club_announcements" ON public.club_announcements;
CREATE POLICY "Admin can update club_announcements"
  ON public.club_announcements FOR UPDATE
  USING (EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin'));

DROP POLICY IF EXISTS "Club admin can update own club_announcements" ON public.club_announcements;
CREATE POLICY "Club admin can update own club_announcements"
  ON public.club_announcements FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.user_id = auth.uid() AND ur.role = 'club_admin' AND ur.club_id = club_announcements.club_id
    )
  );

DROP POLICY IF EXISTS "Admin can delete club_announcements" ON public.club_announcements;
CREATE POLICY "Admin can delete club_announcements"
  ON public.club_announcements FOR DELETE
  USING (EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin'));

DROP POLICY IF EXISTS "Club admin can delete own club_announcements" ON public.club_announcements;
CREATE POLICY "Club admin can delete own club_announcements"
  ON public.club_announcements FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.user_id = auth.uid() AND ur.role = 'club_admin' AND ur.club_id = club_announcements.club_id
    )
  );


-- ---------------------------------------------------------------------------
-- 8. FUNCTION: allow admins to assign roles from the app
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.assign_user_role(
  target_user_id uuid,
  new_role text,
  new_club_id bigint DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  is_caller_admin boolean;
BEGIN
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = auth.uid() AND role = 'admin'
  ) INTO is_caller_admin;

  IF NOT is_caller_admin THEN
    RETURN jsonb_build_object('success', false, 'error', 'Only admins can assign roles');
  END IF;

  IF new_role NOT IN ('admin', 'club_admin') THEN
    RETURN jsonb_build_object('success', false, 'error', 'Invalid role');
  END IF;

  IF new_role = 'club_admin' AND new_club_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'club_id required for club_admin');
  END IF;

  INSERT INTO public.user_roles (user_id, role, club_id)
  VALUES (target_user_id, new_role, CASE WHEN new_role = 'admin' THEN NULL ELSE new_club_id END)
  ON CONFLICT (user_id) DO UPDATE
  SET role = excluded.role, club_id = excluded.club_id;

  RETURN jsonb_build_object('success', true);
EXCEPTION
  WHEN OTHERS THEN
    RETURN jsonb_build_object('success', false, 'error', sqlerrm);
END;
$$;

GRANT EXECUTE ON FUNCTION public.assign_user_role(uuid, text, bigint) TO authenticated;


-- ---------------------------------------------------------------------------
-- 9. GRANTS (anon + authenticated)
-- ---------------------------------------------------------------------------

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT ON public.international_programs TO anon, authenticated;
GRANT SELECT ON public.clubs TO anon, authenticated;
GRANT SELECT ON public.announcements TO anon, authenticated;
GRANT SELECT ON public.club_announcements TO anon, authenticated;
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.international_programs TO authenticated;
GRANT ALL ON public.clubs TO authenticated;
GRANT ALL ON public.announcements TO authenticated;
GRANT ALL ON public.club_announcements TO authenticated;


-- ---------------------------------------------------------------------------
-- 10. ADD YOUR FIRST ADMIN (run separately after Step 11)
-- ---------------------------------------------------------------------------
-- First run the query in section 11 to get user UUIDs. Then uncomment ONE line below
-- and replace YOUR-USER-UUID with the actual id (e.g. a1b2c3d4-e5f6-7890-abcd-ef1234567890).

-- INSERT INTO public.user_roles (user_id, role) VALUES ('YOUR-USER-UUID', 'admin');
-- INSERT INTO public.user_roles (user_id, role, club_id) VALUES ('YOUR-USER-UUID', 'club_admin', 1);


-- ---------------------------------------------------------------------------
-- 11. List auth users (run this to get UUIDs for section 10)
-- ---------------------------------------------------------------------------

SELECT id, email, created_at
FROM auth.users
ORDER BY created_at DESC;
