-- ============================================================
-- Run this in Supabase SQL Editor (Dashboard > SQL Editor)
-- ============================================================

-- 1. Tables (as provided, with announcements primary key fixed)
-- ------------------------------------------------------------

create table if not exists public.international_programs (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  image_url text null default 'https://stock.adobe.com/search?k=no+image'::text,
  name_line1 text null,
  name_line2 text null,
  constraint international_programs_pkey primary key (id)
) tablespace pg_default;

create table if not exists public.clubs (
  id bigint generated by default as identity not null,
  name text null,
  description text null,
  image_url text null,
  created_at timestamp with time zone not null default (now() at time zone 'utc'::text),
  managed_by text null,
  constraint clubs_pkey primary key (id)
) tablespace pg_default;

create table if not exists public.announcements (
  id bigint generated by default as identity not null,
  title text not null,
  subtitle text null,
  image_url text not null default 'https://stock.adobe.com/th/search?k=image'::text,
  date date null default now(),
  see_more_url text null,
  category text null,
  created_at timestamp with time zone null,
  club_id bigint null,
  constraint announcements_pkey primary key (id),
  constraint announcements_club_id_fkey foreign key (club_id) references public.clubs (id)
) tablespace pg_default;

-- 2. User roles: links auth.users to role and optional club (for club admins)
-- ---------------------------------------------------------------------------

create table if not exists public.user_roles (
  id bigint generated by default as identity not null,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null check (role in ('admin', 'club_admin')),
  club_id bigint null references public.clubs (id) on delete set null,
  created_at timestamp with time zone not null default now(),
  constraint user_roles_pkey primary key (id),
  constraint user_roles_user_id_key unique (user_id)
) tablespace pg_default;

comment on table public.user_roles is 'Stores admin vs club_admin role; club_id set only for club_admin.';

-- 3. Enable Row Level Security (RLS) on all tables
-- ------------------------------------------------

alter table public.international_programs enable row level security;
alter table public.clubs enable row level security;
alter table public.announcements enable row level security;
alter table public.user_roles enable row level security;

-- 4. Helper: current user's role (admin / club_admin) and club_id
-- ---------------------------------------------------------------

create or replace function public.current_user_role()
returns table (role text, club_id bigint)
language sql
security definer
stable
set search_path = public
as $$
  select ur.role, ur.club_id
  from public.user_roles ur
  where ur.user_id = auth.uid();
$$;

-- 5. RLS policies: user_roles (users can read their own row only)
-- ---------------------------------------------------------------

create policy "Users can read own role"
  on public.user_roles for select
  using (auth.uid() = user_id);

-- Only superuser or service role should insert/update/delete user_roles (e.g. via Dashboard or backend).
-- No policy for insert/update/delete = only service role can do it.

-- 6. RLS policies: international_programs
-- ---------------------------------------
-- Public read; only admin can insert/update/delete.

create policy "Anyone can read international_programs"
  on public.international_programs for select
  using (true);

create policy "Admin can insert international_programs"
  on public.international_programs for insert
  with check (
    exists (select 1 from public.user_roles where user_id = auth.uid() and role = 'admin')
  );

create policy "Admin can update international_programs"
  on public.international_programs for update
  using (
    exists (select 1 from public.user_roles where user_id = auth.uid() and role = 'admin')
  );

create policy "Admin can delete international_programs"
  on public.international_programs for delete
  using (
    exists (select 1 from public.user_roles where user_id = auth.uid() and role = 'admin')
  );

-- 7. RLS policies: clubs
-- ----------------------
-- Public read; only admin can insert/update/delete. Club admins can only read (to see list and their club).

create policy "Anyone can read clubs"
  on public.clubs for select
  using (true);

create policy "Admin can insert clubs"
  on public.clubs for insert
  with check (
    exists (select 1 from public.user_roles where user_id = auth.uid() and role = 'admin')
  );

create policy "Admin can update clubs"
  on public.clubs for update
  using (
    exists (select 1 from public.user_roles where user_id = auth.uid() and role = 'admin')
  );

create policy "Admin can delete clubs"
  on public.clubs for delete
  using (
    exists (select 1 from public.user_roles where user_id = auth.uid() and role = 'admin')
  );

-- 8. RLS policies: announcements
-- -------------------------------
-- Public read. Admin: full access. Club admin: only rows where club_id = their club_id.

create policy "Anyone can read announcements"
  on public.announcements for select
  using (true);

create policy "Admin can insert announcements"
  on public.announcements for insert
  with check (
    exists (select 1 from public.user_roles where user_id = auth.uid() and role = 'admin')
  );

-- Club admin can only insert announcements for their club (new row's club_id must match their club_id)
create policy "Club admin can insert own club announcements"
  on public.announcements for insert
  with check (
    exists (
      select 1 from public.user_roles ur
      where ur.user_id = auth.uid() and ur.role = 'club_admin' and ur.club_id is not null and ur.club_id = announcements.club_id
    )
  );

create policy "Admin can update announcements"
  on public.announcements for update
  using (
    exists (select 1 from public.user_roles where user_id = auth.uid() and role = 'admin')
  );

create policy "Club admin can update own club announcements"
  on public.announcements for update
  using (
    exists (
      select 1 from public.user_roles ur
      where ur.user_id = auth.uid() and ur.role = 'club_admin' and ur.club_id = announcements.club_id
    )
  );

create policy "Admin can delete announcements"
  on public.announcements for delete
  using (
    exists (select 1 from public.user_roles where user_id = auth.uid() and role = 'admin')
  );

create policy "Club admin can delete own club announcements"
  on public.announcements for delete
  using (
    exists (
      select 1 from public.user_roles ur
      where ur.user_id = auth.uid() and ur.role = 'club_admin' and ur.club_id = announcements.club_id
    )
  );

-- 9. Grant usage to anon and authenticated (Supabase default roles)
-- ------------------------------------------------------------------

grant usage on schema public to anon, authenticated;
grant select on public.international_programs to anon, authenticated;
grant select on public.clubs to anon, authenticated;
grant select on public.announcements to anon, authenticated;
grant select on public.user_roles to authenticated;
grant all on public.international_programs to authenticated;
grant all on public.clubs to authenticated;
grant all on public.announcements to authenticated;

-- 10. Example: add an admin user (run manually after you have a user id from Auth)
-- -------------------------------------------------------------------------------
-- insert into public.user_roles (user_id, role) values ('<auth-users-uuid>', 'admin');
-- insert into public.user_roles (user_id, role, club_id) values ('<auth-users-uuid>', 'club_admin', 1);
